<?php

namespace MyHotelService\Repositories;

use MyHotelService\Entities\Categories;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{ }
