<?php

namespace MyHotelService\Repositories;

use MyHotelService\Entities\Hotels;

/**
 * HotelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelsRepository extends \Doctrine\ORM\EntityRepository
{ }
