<?php

namespace MyHotelService\Repositories;

use MyHotelService\Entities\Reservations;

/**
 * ReservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationsRepository extends \Doctrine\ORM\EntityRepository
{ }
