<?php

namespace MyHotelService\Repositories;

use MyHotelService\Entities\Rooms;

/**
 * RoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsRepository extends \Doctrine\ORM\EntityRepository
{ }
