<?php

namespace MyHotelService\Repositories;

Use MyHotelService\Entities\Users;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
}
